#!/usr/bin/env bash
# Run the independent DynamoDB conformance suite (paritysuite.org,
# github.com/paritysuite/dynamodb-conformance) against a fakecloud binary and
# gate on regressions.
#
# Every test in that suite was recorded against live DynamoDB, so a failure
# means fakecloud answers differently from AWS. Failures fakecloud is known to
# have are listed in scripts/dynamodb-conformance-known-failures.txt; the gate
# fails when a test outside that list fails (a regression) and when a listed
# test now passes (the list is stale and must shrink with the fix).
#
# Usage:
#   scripts/dynamodb-conformance.sh [path/to/fakecloud]        # gate
#   scripts/dynamodb-conformance.sh --update [path/to/fakecloud]  # rewrite the list
#
# Needs git, node (>= 24), npm and jq on PATH.
set -euo pipefail

SUITE_REPO="https://github.com/paritysuite/dynamodb-conformance"
# Pinned so upstream test changes land here as a deliberate bump, not as a
# surprise red build.
SUITE_REF="0178c8e0f182fc82e4475f501017e75e88546cfb"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KNOWN="$ROOT/scripts/dynamodb-conformance-known-failures.txt"

update=0
if [ "${1:-}" = "--update" ]; then
  update=1
  shift
fi
BIN="${1:-$ROOT/target/debug/fakecloud}"
PORT="${DDB_CONFORMANCE_PORT:-4599}"
WORK="${DDB_CONFORMANCE_DIR:-$ROOT/target/dynamodb-conformance}"

if [ ! -x "$BIN" ]; then
  echo "fakecloud binary not found at $BIN (run cargo build --bin fakecloud)" >&2
  exit 2
fi

suite="$WORK/suite"
if [ "$(git -C "$suite" rev-parse HEAD 2>/dev/null || true)" != "$SUITE_REF" ]; then
  rm -rf "$suite"
  git init -q "$suite"
  git -C "$suite" fetch -q --depth 1 "$SUITE_REPO" "$SUITE_REF"
  git -C "$suite" checkout -q FETCH_HEAD
fi
(cd "$suite" && npm ci --silent --no-audit --no-fund)

log="$WORK/fakecloud.log"
FAKECLOUD_CONTAINER_CLI=false "$BIN" --addr "127.0.0.1:$PORT" --log-level warn >"$log" 2>&1 &
server=$!
trap 'kill "$server" 2>/dev/null || true' EXIT

for _ in $(seq 1 120); do
  curl -sf "http://127.0.0.1:$PORT/_fakecloud/health" >/dev/null && break
  if ! kill -0 "$server" 2>/dev/null; then
    echo "fakecloud exited during startup:" >&2
    cat "$log" >&2
    exit 2
  fi
  sleep 0.5
done

report="$WORK/results.json"
rm -f "$report"
# vitest exits non-zero whenever any test fails; the report is what we judge.
(cd "$suite" && DYNAMODB_ENDPOINT="http://127.0.0.1:$PORT" AWS_REGION=us-east-1 \
  AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test \
  npx vitest run --reporter=json --outputFile="$report" >"$WORK/vitest.log" 2>&1) || true

if [ ! -s "$report" ]; then
  echo "suite produced no report; vitest output:" >&2
  tail -50 "$WORK/vitest.log" >&2
  exit 2
fi

# One line per test: "<path under tests/> :: <full name>".
list() {
  jq -r --arg status "$1" '.testResults[] | (.name | sub(".*/tests/"; "")) as $f
    | .assertionResults[] | select(.status == $status) | "\($f) :: \(.fullName)"' "$report" | LC_ALL=C sort -u
}
failed="$(list failed)"
passed="$(list passed)"
total=$(jq '.numTotalTests' "$report")
nfail=$(printf '%s' "$failed" | grep -c . || true)
nskip=$(jq '.numPendingTests + .numTodoTests' "$report")
echo "DynamoDB conformance: $((total - nfail - nskip)) passed, $nfail failed, $nskip skipped of $total"

if [ "$update" = 1 ]; then
  {
    echo "# Tests from the paritysuite DynamoDB conformance suite that fakecloud"
    echo "# currently fails. Generated by scripts/dynamodb-conformance.sh --update;"
    echo "# fix a test and remove its line, never add one to hide a regression."
    [ -n "$failed" ] && printf '%s\n' "$failed"
  } >"$KNOWN"
  echo "wrote $nfail entries to $KNOWN"
  exit 0
fi

known="$(grep -v '^#' "$KNOWN" | grep . | LC_ALL=C sort -u || true)"
regressions="$(LC_ALL=C comm -23 <(printf '%s\n' "$failed" | grep .) <(printf '%s\n' "$known") || true)"
fixed="$(LC_ALL=C comm -12 <(printf '%s\n' "$passed" | grep .) <(printf '%s\n' "$known") || true)"

status=0
if [ -n "$regressions" ]; then
  echo
  echo "New failures (fakecloud now answers differently from DynamoDB):"
  printf '  %s\n' "$regressions"
  status=1
fi
if [ -n "$fixed" ]; then
  echo
  echo "Now passing but still listed in scripts/dynamodb-conformance-known-failures.txt"
  echo "(remove these lines, or rerun with --update):"
  printf '  %s\n' "$fixed"
  status=1
fi
exit "$status"
